[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# הסרת processing rules שיכולים לגרום לבעיות
[build.processing]
  skip_processing = true

# Redirects
[[redirects]]
  from = "/data-recovery"
  to = "/services/data-recovery"
  status = 301

[[redirects]]
  from = "/remote-support"
  to = "/services/remote-support"
  status = 301

[[redirects]]
  from = "/system-repair"
  to = "/services/system-repair"
  status = 301

[[redirects]]
  from = "http://recoverysite.netlify.app/*"
  to = "https://recoverysite.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - חשוב!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
  RESEND_API_KEY = "${RESEND_API_KEY}"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Headers פשוטים יותר
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"