[build]
  command = "npm install && npm run build && npm run debug:build"
  functions = "netlify/functions"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Force HTTPS redirect
[[redirects]]
  from = "http://recoverysite.netlify.app/*"
  to = "https://recoverysite.netlify.app/:splat"
  status = 301
  force = true

# Serverless function rewrite
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA redirect handled in _redirects file to avoid conflicts

# Function configuration
[functions]
  node_bundler = "esbuild"

# Environment variables (will be overridden by actual env vars in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  RESEND_API_KEY = "${RESEND_API_KEY}"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Headers for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for assets directory
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# Headers for serverless functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache"