[build]
  command = "npm install && npm run build && npm run debug:build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/data-recovery"
  to = "/services/data-recovery"
  status = 301

[[redirects]]
  from = "/remote-support"
  to = "/services/remote-support"
  status = 301

[[redirects]]
  from = "/system-repair"
  to = "/services/system-repair"
  status = 301

[[redirects]]
  from = "http://recoverysite.netlify.app/*"
  to = "https://recoverysite.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NODE_ENV = "production"
  RESEND_API_KEY = "${RESEND_API_KEY}"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Cache-Control = "no-cache"
